spring:
  application:
    name: expert-application
  profiles:
    group:
      local:
        - "datasource-local"
        - "logging-local"
      prod:
        - "datasource-prod"
        - "logging-prod"
    active: prod
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application.logging.yml
      - classpath:application-secret.yml