name: EC2에 배포하기

on:
  push:
    branches:
      - feat/**
      - fix/**
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: sudo chmod +x ./gradlew
      - name: Build gradle
        run: sudo ./gradlew clean build -x test
        env:
          MYSQL_ENDPOINT: ${{ secrets.MYSQL_ENDPOINT }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ACCESS-KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_PRIVATE-KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: 빌드된 파일 이름 변경
        run: sudo mv ./build/libs/*SNAPSHOT.jar ./app.jar

      - name: .jar 파일을 EC2 서버에 올리기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/app.jar"
          target: "~"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy application on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar app.jar > /dev/null 2>&1 &